// It's very important that all error-handling code here be as minimal and
// self contained as possible to ensure that the error handling does not
// itself have errors.

const {app, dialog} = require('electron');

const APP_NAME = 'TurboWarp Desktop';
const stringifyError = (error) => (error && error.stack) ? error.stack : error;

try {
  process.on('unhandledRejection', (error) => {
    console.error('Error in promise:', error);
    app.whenReady().then(() => {
      dialog.showMessageBoxSync({
        type: 'error',
        title: APP_NAME,
        message: `Error in promise: ${stringifyError(error)}`
      });
    });
  });

  require('./index');
} catch (error) {
  console.error('Error starting main process:', error);
  app.whenReady().then(() => {
    dialog.showMessageBoxSync({
      type: 'error',
      title: APP_NAME,
      message: `Error starting main process: ${stringifyError(error)}`
    });
    app.exit(1);
  });
}
